### PR TITLE
switch to individual exports to facilitate tree-shaking

### PR DESCRIPTION
**Pull request by AutoSponge**
I was able to solve #7 with this rollup config:

```js
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'

export default {
  entry: 'index.js',
  dest: 'bundle.js',
  format: 'iife',
  plugins: [
    resolve(),
    commonjs()
  ]
}
```

### CODE REVIEW

**Comment by hunterloftis** [comment]
Hey, somehow I missed this PR - thanks for providing it! I'll check it out shortly.

**Comment by tunnckoCore** [comment]
Better use ES6 import/export directly! Using the `commonjs` plugin may not work as expected. As I remember, it is kinda "official" that it is better to use es6 instead of cjs.

**Comment by AutoSponge** [comment]
@tunnckoCore I agree but the library author produced cjs format and did not specify a willingness to publish pure ES6. Like I said, I did test the above config for proper tree-shaking.

**Comment by tunnckoCore** [comment]
I don't understand what's the problem in anyway. It's just enough to use Rollup and release 3 bundles, no matter what type your codebase is. I described very great how it can be accomplished and everyone will win, plus real original tree-shaking by The Inventor of it.

**Comment by hunterloftis** [comment]
This convinced me there was enough interest to ship #14; I'd like to avoid config files, and just use package.json for building, for as long as possible.

**Comment by tunnckoCore** [comment]
Nothing will happen from config file of 3-4 lines. :) It's not so scary, but yea i understand such people - i hate this thing about Webpack and Rollup too - they require whole config file for most basic things such as 

```js
const uglify = require('rollup-plugin-uglify')
const gzip = require('rollup-plugin-gzip')

module.exports = {
  plugins: [uglify({ compress: { warnings: false } }), gzip()],
}
```


That's why i started @Rolldown. :)

**Comment by hunterloftis** [comment]
Config files may start 3-4 lines, but they have a tendency to grow ;)

**Comment by tunnckoCore** [comment]
Rollup & Rollup's are exception. In most cases for library creation they are pretty simple, hence Webpack's approach sucks, reminds me Grunt.

**Pull request closed without merging**
